/*
SQLZoo Helpdesk Hard Solutions
*/

--#11
/*
Show the manager and number of calls received for each hour of the day on 2017-08-12
*/
SELECT m.staff_code as Manager, LEFT(call_date,13) AS Hr, COUNT(*) AS cc
FROM Shift 
  JOIN Staff m ON m.staff_code=Shift.manager
  JOIN Staff o ON o.staff_code=Shift.operator
  JOIN Issue ON Issue.taken_by=o.staff_code
GROUP BY 1,2
HAVING LEFT(Hr,10)='2017-08-12'
ORDER BY 2

--#12
/*
80/20 rule. It is said that 80% of the calls are generated by 20% of the callers. 
Is this true? 
What percentage of calls are generated by the most active 20% of callers.
*/
SET @row_number=0;
SELECT 
  SUM(IF(num <= (SELECT 0.2*COUNT(DISTINCT caller_id) FROM Issue), num_calls,0))*100.0/SUM(num_calls) t20pc
FROM (
  SELECT (@row_number:=@row_number+1) as num, caller_id, num_calls 
    FROM (
      SELECT caller_id, COUNT(caller_id) num_calls
      FROM Issue
      GROUP BY 1
      ORDER BY 2 DESC 
    ) a 
  ORDER BY 3 DESC 
) b
